// Generated by TNCF Temanggung-WebApp Builder | Created by @rochmadjeka
// PWA Edition: doPost() added for fetch-based API access

/**
 * ROUTER UTAMA (GET = HTML, POST = API JSON)
 */
function doGet(e) {
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('Tobacco Monitor - Monitoring Perkebunan')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

/**
 * API ENDPOINT untuk PWA (fetch dari GitHub Pages)
 * Menerima POST body: { action: "funcName", args: [...] }
 */
function doPost(e) {
  try {
    var payload = JSON.parse(e.postData.contents);
    var action  = payload.action;
    var args    = payload.args || [];

    var allowedActions = [
      'loginUser', 'destroySession',
      'getFarmers', 'saveFarmer',
      'getLands', 'saveLand',
      'getPlans', 'savePlan', 'deletePlan',
      'getRealizations', 'saveRealization',
      'getPertanamans', 'savePertanaman',
      'getUsers', 'saveUser', 'deleteUser',
      'getPhases', 'savePhase', 'deletePhase',
      'getDashboardDataRaw'
    ];

    if (allowedActions.indexOf(action) === -1) {
      return buildResponse({ success: false, message: 'Action tidak diizinkan: ' + action });
    }

    // Panggil fungsi sesuai action
    var result = this[action].apply(this, args);
    return buildResponse(result);

  } catch (err) {
    return buildResponse({ success: false, message: 'Server error: ' + err.toString() });
  }
}

function buildResponse(data) {
  return ContentService
    .createTextOutput(JSON.stringify(data))
    .setMimeType(ContentService.MimeType.JSON);
}



/**
 * DATABASE SETUP (ROBUST VERSION)
 */
function setupDatabase() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  if (!ss) throw new Error("ERROR: Buka script ini melalui menu 'Extensions > Apps Script' di dalam Google Sheets Anda.");
  
  const tables = [
    { name: 'Farmers', headers: ['id', 'id_trader', 'kode_trader', 'id_petani', 'id_field', 'field_force', 'pic', 'seri', 'nama_koordinator', 'nama_petani', 'nama_alias', 'nik', 'klaster_petani', 'dusun', 'desa', 'kecamatan', 'kabupaten', 'foto', 'created_at'] },
    { name: 'Lands', headers: ['id', 'id_lahan', 'id_petani', 'nama_lahan', 'desa', 'kecamatan', 'kabupaten', 'klaster', 'irigasi', 'tekstur', 'arah_lereng', 'kemiringan', 'ketinggian', 'point_x', 'point_y', 'luas', 'created_at'] },
    { name: 'VisitPlans', headers: ['id', 'user_id', 'field_force', 'date', 'periode_minggu', 'periode_bulan', 'farmer_id', 'farmer_name', 'klaster_gunung', 'klaster_sawah', 'klaster_tegal', 'klaster_lain', 'total_petani', 'fase_kegiatan', 'sasaran', 'status', 'created_at'] },
    { name: 'VisitRealizations', headers: ['id', 'plan_id', 'user_id', 'field_force', 'plan_date', 'periode_minggu', 'periode_bulan', 'farmer_id', 'farmer_name', 'klaster_gunung', 'klaster_sawah', 'klaster_tegal', 'klaster_lain', 'total_petani', 'real_date', 'lokasi', 'foto', 'resume', 'created_at'] },
    { name: 'Users', headers: ['user_id', 'password', 'fullname', 'role'] },
    { name: 'ActivityPhases', headers: ['id', 'name', 'created_at'] },
    { name: 'MonPertanaman', headers: ['id', 'id_trader', 'id_petani', 'id_field', 'field_force', 'pic', 'nama_koordinator', 'nama_petani', 'nama_alias', 'id_lahan', 'klaster_petani', 'nama_lahan', 'desa', 'kecamatan', 'kabupaten', 'klaster_lahan', 'point_x', 'point_y', 'luas', 'tanggal_tanam', 'rafraksi', 'model_tanam', 'jarak_tanam', 'est_populasi', 'varietas_dominan', 'persen_dominan', 'varietas_sekunder', 'persen_sekunder', 'foto_lahan', 'created_at'] },
    { name: 'AuditLog', headers: ['timestamp', 'username', 'action', 'detail'] }
  ];
  
  tables.forEach(t => {
    let sheet = ss.getSheetByName(t.name);
    if (!sheet) {
      sheet = ss.insertSheet(t.name);
      sheet.appendRow(t.headers);
      sheet.setFrozenRows(1);
    } else {
      const lastCol = sheet.getLastColumn();
      if (lastCol === 0) {
        sheet.appendRow(t.headers);
        sheet.setFrozenRows(1);
      } else {
        const headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
        t.headers.forEach(h => {
          if (headers.indexOf(h) === -1) {
            sheet.getRange(1, headers.length + 1).setValue(h);
            headers.push(h);
          }
        });
      }
    }
  });
  
  const userSheet = ss.getSheetByName('Users');
  if (userSheet && userSheet.getLastRow() <= 2) {
    const data = userSheet.getDataRange().getValues();
    let hasAdmin = false;
    for (let i = 1; i < data.length; i++) { if (data[i][0] === 'admin') hasAdmin = true; }
    if (!hasAdmin) {
      userSheet.appendRow(['admin', hashPassword('Admin@2026'), 'Super Admin', 'Admin']);
      userSheet.appendRow(['JJ', hashPassword('Admin@2026'), 'Trader Area JJ', 'Trader']);
    }
  }

  const phaseSheet = ss.getSheetByName('ActivityPhases');
  if (phaseSheet && phaseSheet.getLastRow() <= 1) {
    phaseSheet.appendRow([Date.now(), 'Pembibitan', new Date()]);
    phaseSheet.appendRow([Date.now()+1, 'Pertanaman', new Date()]);
    phaseSheet.appendRow([Date.now()+2, 'Verifikasi Varietas', new Date()]);
  }
}

/**
 * SECURITY & AUTH HELPERS
 */
function hashPassword(password) {
  var rawHash = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password);
  var txtHash = '';
  for (var i = 0; i < rawHash.length; i++) {
    var hashVal = rawHash[i];
    if (hashVal < 0) hashVal += 256;
    if (hashVal.toString(16).length === 1) txtHash += '0';
    txtHash += hashVal.toString(16);
  }
  return txtHash;
}

function generateSessionToken(username, role) {
  var token = Utilities.getUuid();
  CacheService.getScriptCache().put('session_' + token, JSON.stringify({ username: username, role: role, created: new Date().toISOString() }), 28800);
  return token;
}

function validateSession(token) {
  if (!token) return { valid: false, message: 'Token missing' };
  var sessionData = CacheService.getScriptCache().get('session_' + token);
  if (!sessionData) return { valid: false, message: 'Session expired' };
  var parsed = JSON.parse(sessionData);
  return { valid: true, username: parsed.username, role: parsed.role };
}

function destroySession(token) {
  CacheService.getScriptCache().remove('session_' + token);
  return { success: true };
}

function loginUser(username, password) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName('Users');
  if (!sheet) return { success: false, message: 'Jalankan setupDatabase() terlebih dahulu' };
  
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const uidCol = map['user_id'] !== undefined ? map['user_id'] : map['username'];
  const hashedInput = hashPassword(password);
  
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][uidCol]).toLowerCase() === String(username).toLowerCase() && data[i][map['password']] === hashedInput) {
      const role = data[i][map['role']];
      const token = generateSessionToken(data[i][uidCol], role);
      logAction(data[i][uidCol], 'LOGIN', 'Masuk ke sistem');
      return { success: true, token: token, user: { username: data[i][uidCol], fullname: data[i][map['fullname']], role: role } };
    }
  }
  return { success: false, message: 'User ID atau Password salah!' };
}

function logAction(username, action, detail) {
  try { SpreadsheetApp.getActiveSpreadsheet().getSheetByName('AuditLog').appendRow([new Date(), username, action, detail]); } catch (e) {}
}

/**
 * CORE DATA HELPERS
 */
function getColumnMap(sheet) {
  const lastCol = sheet.getLastColumn();
  if (lastCol === 0) return {};
  const headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
  const map = {};
  headers.forEach((h, i) => map[String(h).toLowerCase().trim()] = i);
  return map;
}

function safeDateFormat(value) {
  if (!value || !(value instanceof Date)) return String(value || '');
  return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
}

function getAllowedPetani(auth) {
  const farmerSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Farmers');
  if (!farmerSheet) return new Set();
  const fData = farmerSheet.getDataRange().getValues();
  const fMap = getColumnMap(farmerSheet);
  const allowed = new Set();
  
  const isAdmin = auth.role === 'Admin';
  const isTrader = auth.role === 'Trader';
  const isPIC = auth.role === 'PIC' || auth.role === 'PIC2';
  for(let i=1; i<fData.length; i++) {
    const id_trader = String(fData[i][fMap['id_trader']] || '');
    const pic = String(fData[i][fMap['pic']] || '');
    if (isAdmin) {
      allowed.add(String(fData[i][fMap['id_petani']]));
    } else if (isTrader && id_trader.toLowerCase() === auth.username.toLowerCase()) {
      allowed.add(String(fData[i][fMap['id_petani']]));
    } else if (isPIC) {
      // Jika PIC2, targetnya selalu ROCHMAD JATI K. Jika PIC biasa, targetnya namanya sendiri.
      const targetPIC = (auth.role === 'PIC2' ? 'ROCHMAD JATI K' : auth.username).toLowerCase();
      if (pic.toLowerCase() === targetPIC) {
        allowed.add(String(fData[i][fMap['id_petani']]));
      }
    }
  }
  return allowed;
}

function getAllowedPlans(auth) {
  const allowedPetani = getAllowedPetani(auth);
  const planSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('VisitPlans');
  if (!planSheet) return new Set();
  const pData = planSheet.getDataRange().getValues();
  const pMap = getColumnMap(planSheet);
  const allowedPlans = new Set();
  const isAdmin = auth.role === 'Admin';
  const isTrader = auth.role === 'Trader';
  // PIC2 ditambahkan di sini
  const isPIC = auth.role === 'PIC' || auth.role === 'PIC2';
  for(let i=1; i<pData.length; i++) {
    if (isAdmin) {
      allowedPlans.add(String(pData[i][pMap['id']]));
    } else if (isTrader && String(pData[i][pMap['user_id']]).toLowerCase() === auth.username.toLowerCase()) {
      allowedPlans.add(String(pData[i][pMap['id']]));
    } else if (isPIC) {
      // PIC access depends on if any of the plan's farmers belong to this PIC
      const planFarmers = String(pData[i][pMap['farmer_id']] || '').split(',').map(s => s.trim());
      if (planFarmers.some(fid => allowedPetani.has(fid))) {
        allowedPlans.add(String(pData[i][pMap['id']]));
      }
    }
  }
  return allowedPlans;
}

function uploadImageToDrive(base64Data, filename) {
  try {
    var folders = DriveApp.getFoldersByName("TobaccoMonitor_Photos");
    var folder = folders.hasNext() ?
      folders.next() : DriveApp.createFolder("TobaccoMonitor_Photos");
    var contentType = base64Data.substring(5, base64Data.indexOf(';'));
    var bytes = Utilities.base64Decode(base64Data.split(',')[1]);
    var blob = Utilities.newBlob(bytes, contentType, filename);
    var file = folder.createFile(blob);
    file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
    
    // Memaksa Google Drive memberikan Direct Link Image, bukan Web Viewer
    return 'https://drive.google.com/uc?export=view&id=' + file.getId(); 
  } catch(e) { return '';
  }
}

// ==============================
// DASHBOARD
// ==============================
function getDashboardDataRaw(token) {
  try {
    const auth = validateSession(token);
    if (!auth.valid) return { success: false, sessionExpired: true };
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    
    const allowedPetani = getAllowedPetani(auth);
    const fCount = allowedPetani.size;
    
    const pSheet = ss.getSheetByName('VisitPlans');
    const plans = [];
    
    // Pelindung: Hanya jalankan jika Sheet ada dan ada isinya
    if (pSheet && pSheet.getLastRow() > 1) {
        const planData = pSheet.getDataRange().getValues();
        const pMap = getColumnMap(pSheet);
        for (let i = 1; i < planData.length; i++) {
          if (auth.role === 'Trader' && String(planData[i][pMap['user_id']]).toLowerCase() !== auth.username.toLowerCase()) continue;
          if (auth.role === 'PIC' || auth.role === 'PIC2') {
            const planFarmers = String(planData[i][pMap['farmer_id']] || '').split(',').map(s => s.trim());
            if (!planFarmers.some(fid => allowedPetani.has(fid))) continue;
          }
          
          plans.push({
            date: safeDateFormat(planData[i][pMap['date']]),
            field_force: planData[i][pMap['field_force']] || 'Tanpa Nama',
            status: planData[i][pMap['status']] || 'Pending'
          });
        }
    }
    return { success: true, data: { totalFarmers: fCount, plans: plans } };
  } catch (error) {
    return { success: false, message: "Error Data Backend: " + error.toString() };
  }
}

// ==============================
// FARMER (PARENT) CRUD
// ==============================
function getFarmers(token) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Farmers');
  if (sheet.getLastRow() < 2) return { success: true, data: [] };
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const result = [];
  
  for (let i = data.length - 1; i >= 1; i--) {
    const id_trader = String(data[i][map['id_trader']] || '');
    const pic = String(data[i][map['pic']] || '');
    
    if (auth.role === 'Trader' && id_trader.toLowerCase() !== auth.username.toLowerCase()) continue;
    if (auth.role === 'PIC' || auth.role === 'PIC2') {
      const targetPIC = (auth.role === 'PIC2' ? 'ROCHMAD JATI K' : auth.username).toLowerCase();
      if (pic.toLowerCase() !== targetPIC) continue;
    }
    
    result.push({
      id: data[i][map['id']], id_trader: id_trader, kode_trader: data[i][map['kode_trader']] || '',
      id_petani: data[i][map['id_petani']] || '', id_field: data[i][map['id_field']] || '',
      field_force: data[i][map['field_force']] || '', pic: pic,
      seri: data[i][map['seri']] || '', nama_koordinator: data[i][map['nama_koordinator']] || '',
      nama_petani: data[i][map['nama_petani']] || '', nama_alias: data[i][map['nama_alias']] || '',
      nik: data[i][map['nik']] || '', klaster_petani: data[i][map['klaster_petani']] || '',
      dusun: data[i][map['dusun']] || '', desa: data[i][map['desa']] || '', 
      kecamatan: data[i][map['kecamatan']] || '', kabupaten: data[i][map['kabupaten']] || '', 
      foto: data[i][map['foto']] || ''
    });
  }
  return { success: true, data: result };
}

function saveFarmer(token, payload) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  
  // Lock mechanism based on Role
  if (auth.role === 'Trader') {
    payload.id_trader = auth.username;
  } else if (auth.role === 'PIC' || auth.role === 'PIC2') {
    // If PIC adds a farmer, ensure their name is locked to the PIC field
    payload.pic = auth.username;
  }
  
  if (payload.foto && payload.foto.startsWith('data:image')) {
    var driveUrl = uploadImageToDrive(payload.foto, 'Petani_' + payload.id_petani + '_' + Date.now() + '.jpg');
    if (driveUrl) payload.foto = driveUrl;
  }

  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Farmers');
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    
    if (payload.isEdit === 'true') {
      for (let i = 1; i < data.length; i++) {
        if (data[i][map['id']] == payload.id) {
          // Double check ownership before updating
          if (auth.role === 'Trader' && String(data[i][map['id_trader']]).toLowerCase() !== auth.username.toLowerCase()) return { success: false, message: 'Akses Ditolak' };
          const targetPIC = (auth.role === 'PIC2' ? 'ROCHMAD JATI K' : auth.username).toLowerCase();
    if ((auth.role === 'PIC' || auth.role === 'PIC2') && String(data[i][map['pic']]).toLowerCase() !== targetPIC) return { success: false, message: 'Akses Ditolak' };
          
          for (const key in payload) { if (map[key] !== undefined && key !== 'id' && key !== 'isEdit') { sheet.getRange(i + 1, map[key] + 1).setValue(payload[key]); } }
          break;
        }
      }
    } else {
      const id = Date.now();
      const newRow = new Array(headers.length).fill('');
      newRow[map['id']] = id;
      for (const key in payload) { if (map[key] !== undefined && key !== 'id' && key !== 'isEdit') newRow[map[key]] = payload[key]; }
      if (map['created_at'] !== undefined) newRow[map['created_at']] = new Date();
      sheet.appendRow(newRow);
    }
    logAction(auth.username, 'SAVE_FARMER', payload.nama_petani);
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
  finally { lock.releaseLock(); }
}

// ==============================
// LAND (CHILD) CRUD
// ==============================
function getLands(token) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Lands');
  if (sheet.getLastRow() < 2) return { success: true, data: [] };
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const result = [];
  const allowedPetani = getAllowedPetani(auth);
  
  for (let i = data.length - 1; i >= 1; i--) {
    if (auth.role !== 'Admin' && !allowedPetani.has(String(data[i][map['id_petani']]))) continue;
    result.push({
      id: data[i][map['id']], id_lahan: data[i][map['id_lahan']] || '',
      id_petani: data[i][map['id_petani']] || '', nama_lahan: data[i][map['nama_lahan']] || '',
      desa: data[i][map['desa']] || '', kecamatan: data[i][map['kecamatan']] || '',
      kabupaten: data[i][map['kabupaten']] || '', klaster: data[i][map['klaster']] || '',
      irigasi: data[i][map['irigasi']] || '', tekstur: data[i][map['tekstur']] || '',
      arah_lereng: data[i][map['arah_lereng']] || '', kemiringan: data[i][map['kemiringan']] || '',
      ketinggian: data[i][map['ketinggian']] || '', point_x: data[i][map['point_x']] || '',
      point_y: data[i][map['point_y']] || '', luas: data[i][map['luas']] || ''
    });
  }
  return { success: true, data: result };
}

function saveLand(token, payload) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  const allowedPetani = getAllowedPetani(auth);
  if (auth.role !== 'Admin' && !allowedPetani.has(String(payload.id_petani))) return { success: false, message: 'Akses Ditolak.' };
  
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Lands');
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    if (payload.isEdit === 'true') {
      for (let i = 1; i < data.length; i++) {
        if (data[i][map['id']] == payload.id) {
          for (const key in payload) { if (map[key] !== undefined && key !== 'id' && key !== 'isEdit') sheet.getRange(i + 1, map[key] + 1).setValue(payload[key]); }
          break;
        }
      }
    } else {
      const id = Date.now();
      const newRow = new Array(headers.length).fill('');
      newRow[map['id']] = id;
      for (const key in payload) { if (map[key] !== undefined && key !== 'id' && key !== 'isEdit') newRow[map[key]] = payload[key]; }
      if (map['created_at'] !== undefined) newRow[map['created_at']] = new Date();
      sheet.appendRow(newRow);
    }
    logAction(auth.username, 'SAVE_LAND', payload.nama_lahan);
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
  finally { lock.releaseLock(); }
}

// ==============================
// PLANS & REALIZATION
// ==============================
function getPlans(token) {
  try {
    const auth = validateSession(token);
    if (!auth.valid) return { success: false, sessionExpired: true };
    
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('VisitPlans');
    if (!sheet || sheet.getLastRow() < 2) return { success: true, data: [] };
    
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    const result = [];
    const allowedPetani = getAllowedPetani(auth);
    
    for (let i = data.length - 1; i >= 1; i--) {
      // Filter Trader
      if (auth.role === 'Trader' && String(data[i][map['user_id']]).toLowerCase() !== auth.username.toLowerCase()) continue;
      // Filter PIC dan PIC2
      if (auth.role === 'PIC' || auth.role === 'PIC2') {
        const planFarmers = String(data[i][map['farmer_id']] || '').split(',').map(s => s.trim());
        if (!planFarmers.some(fid => allowedPetani.has(fid))) continue;
      }
      
      // PELINDUNG ANTI-NULL: Memaksa semua output menjadi String (Teks)
      result.push({
        id: String(data[i][map['id']] || ''), 
        user_id: String(data[i][map['user_id']] || ''),
        field_force: String(data[i][map['field_force']] || ''), 
        date: safeDateFormat(data[i][map['date']]),
        periode_minggu: String(data[i][map['periode_minggu']] || ''), 
        periode_bulan: String(data[i][map['periode_bulan']] || ''),
        farmer_id: String(data[i][map['farmer_id']] || ''), 
        farmer_name: String(data[i][map['farmer_name']] || ''),
        klaster_gunung: String(data[i][map['klaster_gunung']] || '0'), 
        klaster_sawah: String(data[i][map['klaster_sawah']] || '0'),
        klaster_tegal: String(data[i][map['klaster_tegal']] || '0'), 
        klaster_lain: String(data[i][map['klaster_lain']] || '0'),
        total_petani: String(data[i][map['total_petani']] || '0'), 
        status: String(data[i][map['status']] || 'Pending')
      });
    }
    return { success: true, data: result };
  } catch (e) {
    return { success: false, message: "Error Backend: " + e.message };
  }
}

function savePlan(token, payload) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('VisitPlans');
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const map = getColumnMap(sheet);
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    
    const id = Date.now();
    const newRow = new Array(headers.length).fill('');
    newRow[map['id']] = id;
    for (const key in payload) {
      if (map[key] !== undefined && key !== 'id') { newRow[map[key]] = payload[key]; }
    }
    if (map['status'] !== undefined) newRow[map['status']] = 'Pending';
    if (map['created_at'] !== undefined) newRow[map['created_at']] = new Date();
    
    sheet.appendRow(newRow);
    logAction(auth.username, 'CREATE_PLAN', payload.periode_minggu);
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
  finally { lock.releaseLock(); }
}

function saveRealization(token, payload) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  const allowedPlans = getAllowedPlans(auth);
  if (auth.role !== 'Admin' && !allowedPlans.has(String(payload.plan_id))) return { success: false, message: 'Akses Ditolak.' };
  
  if (payload.foto && payload.foto.startsWith('data:image')) {
    var driveUrl = uploadImageToDrive(payload.foto, 'Realization_' + payload.plan_id + '_' + Date.now() + '.jpg');
    if (driveUrl) payload.foto = driveUrl;
  }
  
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const planSheet = ss.getSheetByName('VisitPlans');
  const realSheet = ss.getSheetByName('VisitRealizations');
  
  const planData = planSheet.getDataRange().getValues();
  const pMap = getColumnMap(planSheet);
  
  for (let i = 1; i < planData.length; i++) {
    if (planData[i][pMap['id']] == payload.plan_id) {
      planSheet.getRange(i + 1, pMap['status'] + 1).setValue('Visited');
      break;
    }
  }
  
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const map = getColumnMap(realSheet);
    const headers = realSheet.getRange(1, 1, 1, realSheet.getLastColumn()).getValues()[0];
    
    const id = Date.now();
    const newRow = new Array(headers.length).fill('');
    newRow[map['id']] = id;
    for (const key in payload) {
      if (map[key] !== undefined && key !== 'id') { newRow[map[key]] = payload[key]; }
    }
    if (map['created_at'] !== undefined) newRow[map['created_at']] = new Date();
    
    realSheet.appendRow(newRow);
    logAction(auth.username, 'REALIZATION', payload.plan_id);
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
  finally { lock.releaseLock(); }
}

function getRealizations(token) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('VisitRealizations');
  if (sheet.getLastRow() < 2) return { success: true, data: [] };
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const result = [];
  const allowedPlans = getAllowedPlans(auth);
  const isAdmin = auth.role === 'Admin';
  
  for (let i = data.length - 1; i >= 1; i--) {
    if (!isAdmin && !allowedPlans.has(String(data[i][map['plan_id']]))) continue;
    result.push({
      id: data[i][map['id']], user_id: data[i][map['user_id']] || '',
      field_force: data[i][map['field_force']] || '', periode_minggu: data[i][map['periode_minggu']] || '',
      farmer_name: data[i][map['farmer_name']] || '', total_petani: data[i][map['total_petani']] || '',
      real_date: safeDateFormat(data[i][map['real_date']]), resume: data[i][map['resume']] || '',
      lokasi: data[i][map['lokasi']] || '', foto: data[i][map['foto']] || ''
    });
  }
  return { success: true, data: result };
}

function deletePlan(token, id) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  const allowedPlans = getAllowedPlans(auth);
  if (auth.role !== 'Admin' && !allowedPlans.has(String(id))) return { success: false, message: 'Akses Ditolak.' };
  
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('VisitPlans');
  const data = sheet.getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    if (data[i][0] == id) { sheet.deleteRow(i + 1); break; }
  }
  return { success: true };
}

// ==============================
// MONITORING PERTANAMAN
// ==============================
function getPertanamans(token) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('MonPertanaman');
  if (!sheet || sheet.getLastRow() < 2) return { success: true, data: [] };
  
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const result = [];
  const allowedPetani = getAllowedPetani(auth);
  
  for (let i = data.length - 1; i >= 1; i--) {
    if (auth.role !== 'Admin' && !allowedPetani.has(String(data[i][map['id_petani']]))) continue;
    
    let row = { id: data[i][map['id']] };
    Object.keys(map).forEach(k => {
      row[k] = data[i][map[k]];
      if(row[k] instanceof Date) row[k] = safeDateFormat(row[k]);
    });
    result.push(row);
  }
  return { success: true, data: result };
}

function savePertanaman(token, payload) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true };
  
  if (payload.foto_lahan && payload.foto_lahan.startsWith('data:image')) {
    var driveUrl = uploadImageToDrive(payload.foto_lahan, 'Pertanaman_' + payload.id_lahan + '_' + Date.now() + '.jpg');
    if (driveUrl) payload.foto_lahan = driveUrl;
  }
  
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('MonPertanaman');
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    
    if (payload.isEdit === 'true') {
      for (let i = 1; i < data.length; i++) {
        if (String(data[i][map['id']]) === String(payload.id)) {
          for (const key in payload) {
            if (map[key] !== undefined && key !== 'id' && key !== 'isEdit') {
              sheet.getRange(i + 1, map[key] + 1).setValue(payload[key]);
            }
          }
          break;
        }
      }
    } else {
      const id = Date.now();
      const newRow = new Array(headers.length).fill('');
      newRow[map['id']] = id;
      for (const key in payload) {
        if (map[key] !== undefined && key !== 'id' && key !== 'isEdit') newRow[map[key]] = payload[key];
      }
      if (map['created_at'] !== undefined) newRow[map['created_at']] = new Date();
      sheet.appendRow(newRow);
    }
    logAction(auth.username, 'SAVE_PERTANAMAN', payload.id_lahan);
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
  finally { lock.releaseLock(); }
}

// ==============================
// USER & PHASE MANAGEMENT (ADMIN)
// ==============================
function getUsers(token) {
  const auth = validateSession(token);
  if (!auth.valid || auth.role !== 'Admin') return { success: false, sessionExpired: !auth.valid };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const uidCol = map['user_id'] !== undefined ? map['user_id'] : map['username'];
  const result = [];
  for (let i = 1; i < data.length; i++) {
    result.push({ user_id: data[i][uidCol], fullname: data[i][map['fullname']], role: data[i][map['role']] });
  }
  return { success: true, data: result };
}

function saveUser(token, payload) {
  const auth = validateSession(token);
  if (!auth.valid || auth.role !== 'Admin') return { success: false, message: 'Unauthorized' };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    const uidCol = map['user_id'] !== undefined ? map['user_id'] : map['username'];
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    
    if (payload.isEdit === 'true') {
      for (let i = 1; i < data.length; i++) {
        if (String(data[i][uidCol]) === String(payload.old_user_id)) {
          sheet.getRange(i + 1, uidCol + 1).setValue(payload.user_id);
          sheet.getRange(i + 1, map['fullname'] + 1).setValue(payload.fullname);
          sheet.getRange(i + 1, map['role'] + 1).setValue(payload.role);
          if (payload.password) { sheet.getRange(i + 1, map['password'] + 1).setValue(hashPassword(payload.password)); }
          break;
        }
      }
    } else {
      for (let i = 1; i < data.length; i++) {
        if (String(data[i][uidCol]).toLowerCase() === String(payload.user_id).toLowerCase()) return { success: false, message: 'User ID sudah terdaftar!' };
      }
      const newRow = new Array(headers.length).fill('');
      newRow[uidCol] = payload.user_id; newRow[map['password']] = hashPassword(payload.password || 'Trader123');
      newRow[map['fullname']] = payload.fullname; newRow[map['role']] = payload.role;
      sheet.appendRow(newRow);
    }
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
  finally { lock.releaseLock(); }
}

function deleteUser(token, user_id) {
  const auth = validateSession(token);
  if (!auth.valid || auth.role !== 'Admin') return { success: false, message: 'Unauthorized' };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const uidCol = map['user_id'] !== undefined ? map['user_id'] : map['username'];
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][uidCol]) === String(user_id)) {
      if (data[i][map['role']] === 'Admin' && data.filter(r => r[map['role']] === 'Admin').length <= 1) return { success: false, message: 'Tidak bisa menghapus satu-satunya Admin' };
      sheet.deleteRow(i + 1);
      break;
    }
  }
  return { success: true };
}

function getPhases(token) {
  const auth = validateSession(token);
  if (!auth.valid) return { success: false, sessionExpired: true }; 
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('ActivityPhases');
  if (sheet.getLastRow() < 2) return { success: true, data: [] };
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  const result = [];
  for (let i = 1; i < data.length; i++) {
    result.push({ id: data[i][map['id']], name: data[i][map['name']] });
  }
  return { success: true, data: result };
}

function savePhase(token, payload) {
  const auth = validateSession(token);
  if (!auth.valid || auth.role !== 'Admin') return { success: false, message: 'Unauthorized' };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('ActivityPhases');
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    if (payload.isEdit === 'true') {
      for (let i = 1; i < data.length; i++) {
        if (String(data[i][map['id']]) === String(payload.id)) {
          sheet.getRange(i + 1, map['name'] + 1).setValue(payload.name);
          break;
        }
      }
    } else {
      sheet.appendRow([Date.now(), payload.name, new Date()]);
    }
    return { success: true };
  } catch(e) { return { success: false, message: e.toString() }; }
  finally { lock.releaseLock(); }
}

function deletePhase(token, id) {
  const auth = validateSession(token);
  if (!auth.valid || auth.role !== 'Admin') return { success: false, message: 'Unauthorized' };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('ActivityPhases');
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][map['id']]) === String(id)) {
      sheet.deleteRow(i + 1);
      break;
    }
  }
  return { success: true };
}
